import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorial: [{type: "autogenerated", dirName: "."}],

  tutorial: [
    "introduction",
    "tutorial/install",
    {
      type: "category",
      label: "Usages",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Use pyDocusaurus",
        slug: "/category/usages",
        description:
          "Understand the formats and usages of pyDocusaurus.",
      },
      items: [
        "tutorial/usages/get-started",
        "tutorial/usages/special-types",
        "tutorial/usages/rendering",
      ],
    },
    "tutorial/examples",
    "license",
  ],

  apis: [
    "apis/index",
    {
      "type": "category",
      "label": "renderer",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/renderer/index"
      },
      "items": [
        {
          "type": "category",
          "label": "page",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/renderer/page/index"
          },
          "items": [
            "apis/renderer/page/render_obj",
            "apis/renderer/page/RendererPage"
          ]
        },
        {
          "type": "category",
          "label": "package",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/renderer/package/index"
          },
          "items": [
            "apis/renderer/package/render_package_as_mdx",
            "apis/renderer/package/PackageInformation",
            "apis/renderer/package/URIHolder",
            "apis/renderer/package/PackageRenderer"
          ]
        },
        {
          "type": "category",
          "label": "components",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/renderer/components/index"
          },
          "items": [
            "apis/renderer/components/CompModule",
            "apis/renderer/components/Components"
          ]
        },
        {
          "type": "category",
          "label": "resources",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/renderer/resources/index"
          },
          "items": [
            "apis/renderer/resources/is_jinja_template",
            "apis/renderer/resources/get_jinja_template_out_name",
            "apis/renderer/resources/ts_object",
            "apis/renderer/resources/as_pypi_name",
            "apis/renderer/resources/render_resource_tree"
          ]
        },
        {
          "type": "category",
          "label": "saver",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/renderer/saver/index"
          },
          "items": [
            "apis/renderer/saver/SaverAbstract",
            "apis/renderer/saver/SaverDefault"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "components",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/components/index"
      },
      "items": [
        {
          "type": "category",
          "label": "apibar",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/components/apibar/index"
          },
          "items": [
            "apis/components/apibar/ComponentAPIBar"
          ]
        },
        {
          "type": "category",
          "label": "comprotocol",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/components/comprotocol/index"
          },
          "items": [
            "apis/components/comprotocol/ProtocolComponent"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "core",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/core/index"
      },
      "items": [
        {
          "type": "category",
          "label": "walker",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/walker/index"
          },
          "items": [
            "apis/core/walker/PackageWalker",
            "apis/core/walker/analyze_module_ast",
            "apis/core/walker/get_direct_submodules",
            "apis/core/walker/is_direct_nonmodule",
            "apis/core/walker/is_direct_module",
            "apis/core/walker/is_direct_member",
            "apis/core/walker/is_main_module",
            "apis/core/walker/fast_import",
            "apis/core/walker/ParserAbstract"
          ]
        },
        {
          "type": "category",
          "label": "analyzer",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/analyzer/index"
          },
          "items": [
            "apis/core/analyzer/is_single_paragraph"
          ]
        },
        {
          "type": "category",
          "label": "attree",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/attree/index"
          },
          "items": [
            "apis/core/attree/AttributeTreeNode",
            "apis/core/attree/ModuleAttributeTree",
            "apis/core/attree/build_sidebar"
          ]
        },
        {
          "type": "category",
          "label": "classes",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/classes/index"
          },
          "items": [
            "apis/core/classes/AbstractAttrs",
            "apis/core/classes/ClassProfile",
            "apis/core/classes/DocProp",
            "apis/core/classes/DocClass",
            "apis/core/classes/parse_prop_docs",
            "apis/core/classes/parse_class_docs"
          ]
        },
        {
          "type": "category",
          "label": "datacls",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/datacls/index"
          },
          "items": [
            "apis/core/datacls/DocField",
            "apis/core/datacls/DocDataClass",
            "apis/core/datacls/parse_dataclass_docs"
          ]
        },
        {
          "type": "category",
          "label": "enums",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/enums/index"
          },
          "items": [
            "apis/core/enums/DocEnumItem",
            "apis/core/enums/DocEnum",
            "apis/core/enums/parse_enum_docs"
          ]
        },
        {
          "type": "category",
          "label": "functions",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/functions/index"
          },
          "items": [
            "apis/core/functions/ParameterKind",
            "apis/core/functions/FunctionType",
            "apis/core/functions/DocArgument",
            "apis/core/functions/DocFunction",
            "apis/core/functions/parse_argument_docs",
            "apis/core/functions/parse_return_docs",
            "apis/core/functions/parse_func_docs"
          ]
        },
        {
          "type": "category",
          "label": "inspectors",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/inspectors/index"
          },
          "items": [
            "apis/core/inspectors/get_mro",
            "apis/core/inspectors/get_obj_slang",
            "apis/core/inspectors/is_user_defined_method",
            "apis/core/inspectors/get_members_defined_in_class",
            "apis/core/inspectors/get_members_defined_in_enum",
            "apis/core/inspectors/get_field_docstrings",
            "apis/core/inspectors/get_arg_default_name",
            "apis/core/inspectors/get_lambda_source",
            "apis/core/inspectors/get_func_signature",
            "apis/core/inspectors/get_field_default",
            "apis/core/inspectors/is_multival_tuple",
            "apis/core/inspectors/is_member_abstract",
            "apis/core/inspectors/is_func_yield",
            "apis/core/inspectors/unwrap_annotated_annotation",
            "apis/core/inspectors/unpack_annotation",
            "apis/core/inspectors/strip_annotation_name",
            "apis/core/inspectors/get_short_descr",
            "apis/core/inspectors/get_slug",
            "apis/core/inspectors/relative_url_path"
          ]
        },
        {
          "type": "category",
          "label": "modules",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/modules/index"
          },
          "items": [
            "apis/core/modules/DocModuleProp",
            "apis/core/modules/DocModuleMetadata",
            "apis/core/modules/DocModule",
            "apis/core/modules/parse_module_doc"
          ]
        },
        {
          "type": "category",
          "label": "ops",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/ops/index"
          },
          "items": [
            "apis/core/ops/unwrap_top_level_typehint",
            "apis/core/ops/DocOpTemplate"
          ]
        },
        {
          "type": "category",
          "label": "protocols",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/protocols/index"
          },
          "items": [
            "apis/core/protocols/DocProtocol",
            "apis/core/protocols/parse_protocol_docs"
          ]
        },
        {
          "type": "category",
          "label": "texts",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/texts/index"
          },
          "items": [
            "apis/core/texts/santize_doc_cell",
            "apis/core/texts/Section",
            "apis/core/texts/Table"
          ]
        },
        {
          "type": "category",
          "label": "typealiases",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/typealiases/index"
          },
          "items": [
            "apis/core/typealiases/DocTypeAlias",
            "apis/core/typealiases/is_generic_type_alias_call",
            "apis/core/typealiases/is_runtime_root",
            "apis/core/typealiases/is_possibly_type_expression",
            "apis/core/typealiases/parse_type_aliases_doc"
          ]
        },
        {
          "type": "category",
          "label": "typeddicts",
          "collapsed": true,
          "link": {
            "type": "doc",
            "id": "apis/core/typeddicts/index"
          },
          "items": [
            "apis/core/typeddicts/DocTypedDictItem",
            "apis/core/typeddicts/DocTypedDict",
            "apis/core/typeddicts/parse_typeddict_doc"
          ]
        }
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
