blank_issues_enabled: false
contact_links:
  - name: Review the Documentation
    url: https://cainmagi.github.io/diff-nlp/
    about: Check whether your issue has been answered by the documentation.
