import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: "autogenerated", dirName: "."}],

  apis: [
    "apis/index",
    {
      "type": "category",
      "label": "funcs",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/funcs/index"
      },
      "items": [
        "apis/funcs/example_complicated_func",
        "apis/funcs/example_iterator_func",
        "apis/funcs/example_overload_func"
      ]
    },
    "apis/ExampleRootClass",
    "apis/example_root_func",
    {
      "type": "category",
      "label": "classes",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/classes/index"
      },
      "items": [
        "apis/classes/ExampleClass",
        "apis/classes/ExampleModel",
        "apis/classes/ExampleEnum"
      ]
    },
    {
      "type": "category",
      "label": "subpackage",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/subpackage/index"
      },
      "items": [
        "apis/subpackage/ExampleAnno",
        "apis/subpackage/empty_function"
      ]
    },
    {
      "type": "category",
      "label": "typecls",
      "collapsed": true,
      "link": {
        "type": "doc",
        "id": "apis/typecls/index"
      },
      "items": [
        "apis/typecls/CustomType",
        "apis/typecls/SpecifiedList",
        "apis/typecls/ComplicatedList",
        "apis/typecls/ExampleDict",
        "apis/typecls/ExampleProtocol"
      ]
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
